package pojo;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "gestion_gite")
public class Adresse implements java.io.Serializable {

	private Integer idAdresse;
	private Pays pays;
	private String rue;
	private String nr;
	private String zip;
	private String localite;
	private Set<Client> clients = new HashSet<Client>(0);

	public Adresse() {
	}

	public Adresse(Pays pays, String rue, String nr, String zip, String localite) {
		this.pays = pays;
		this.rue = rue;
		this.nr = nr;
		this.zip = zip;
		this.localite = localite;
	}

	public Adresse(Pays pays, String rue, String nr, String zip,
			String localite, Set<Client> clients) {
		this.pays = pays;
		this.rue = rue;
		this.nr = nr;
		this.zip = zip;
		this.localite = localite;
		this.clients = clients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAdresse", unique = true, nullable = false)
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPays", nullable = false)
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@Column(name = "rue", nullable = false, length = 100)
	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	@Column(name = "nr", nullable = false, length = 5)
	public String getNr() {
		return this.nr;
	}

	public void setNr(String nr) {
		this.nr = nr;
	}

	@Column(name = "zip", nullable = false, length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "localite", nullable = false, length = 50)
	public String getLocalite() {
		return this.localite;
	}

	public void setLocalite(String localite) {
		this.localite = localite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
