package pojo;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetailreservationId generated by hbm2java
 */
@Embeddable
public class DetailreservationId implements java.io.Serializable {

	private int idTypeLocation;
	private int idReservation;

	public DetailreservationId() {
	}

	public DetailreservationId(int idTypeLocation, int idReservation) {
		this.idTypeLocation = idTypeLocation;
		this.idReservation = idReservation;
	}

	@Column(name = "idTypeLocation", nullable = false)
	public int getIdTypeLocation() {
		return this.idTypeLocation;
	}

	public void setIdTypeLocation(int idTypeLocation) {
		this.idTypeLocation = idTypeLocation;
	}

	@Column(name = "idReservation", nullable = false)
	public int getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(int idReservation) {
		this.idReservation = idReservation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailreservationId))
			return false;
		DetailreservationId castOther = (DetailreservationId) other;

		return (this.getIdTypeLocation() == castOther.getIdTypeLocation())
				&& (this.getIdReservation() == castOther.getIdReservation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTypeLocation();
		result = 37 * result + this.getIdReservation();
		return result;
	}

}
