package pojo;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detailreservation generated by hbm2java
 */
@Entity
@Table(name = "detailreservation", catalog = "gestion_gite")
public class Detailreservation implements java.io.Serializable {

	private DetailreservationId id;
	private Reservation reservation;
	private Typelocation typelocation;
	private int nbjours;
	private double prix;

	public Detailreservation() {
	}

	public Detailreservation(DetailreservationId id, Reservation reservation,
			Typelocation typelocation, int nbjours, double prix) {
		this.id = id;
		this.reservation = reservation;
		this.typelocation = typelocation;
		this.nbjours = nbjours;
		this.prix = prix;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idTypeLocation", column = @Column(name = "idTypeLocation", nullable = false)),
			@AttributeOverride(name = "idReservation", column = @Column(name = "idReservation", nullable = false)) })
	public DetailreservationId getId() {
		return this.id;
	}

	public void setId(DetailreservationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idReservation", nullable = false, insertable = false, updatable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTypeLocation", nullable = false, insertable = false, updatable = false)
	public Typelocation getTypelocation() {
		return this.typelocation;
	}

	public void setTypelocation(Typelocation typelocation) {
		this.typelocation = typelocation;
	}

	@Column(name = "nbjours", nullable = false)
	public int getNbjours() {
		return this.nbjours;
	}

	public void setNbjours(int nbjours) {
		this.nbjours = nbjours;
	}

	@Column(name = "prix", nullable = false, precision = 22, scale = 0)
	public double getPrix() {
		return this.prix;
	}

	public void setPrix(double prix) {
		this.prix = prix;
	}

}
