package pojo;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Moderateur generated by hbm2java
 */
@Entity
@Table(name = "moderateur", catalog = "gestion_gite")
public class Moderateur implements java.io.Serializable {

	private int idModerateur;
	private Personne personne;
	private String contrat;
	private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);

	public Moderateur() {
	}

	public Moderateur(Personne personne, String contrat) {
		this.personne = personne;
		this.contrat = contrat;
	}

	public Moderateur(Personne personne, String contrat,
			Set<Commentaire> commentaires) {
		this.personne = personne;
		this.contrat = contrat;
		this.commentaires = commentaires;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personne"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idModerateur", unique = true, nullable = false)
	public int getIdModerateur() {
		return this.idModerateur;
	}

	public void setIdModerateur(int idModerateur) {
		this.idModerateur = idModerateur;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@Column(name = "contrat", nullable = false, length = 20)
	public String getContrat() {
		return this.contrat;
	}

	public void setContrat(String contrat) {
		this.contrat = contrat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moderateur")
	public Set<Commentaire> getCommentaires() {
		return this.commentaires;
	}

	public void setCommentaires(Set<Commentaire> commentaires) {
		this.commentaires = commentaires;
	}

}
