package pojo;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Specialite generated by hbm2java
 */
@Entity
@Table(name = "specialite", catalog = "gestion_gite")
public class Specialite implements java.io.Serializable {

	private Integer idSpecialite;
	private String nomSpecialite;
	private String commentaire;
	private Set<Gite> gites = new HashSet<Gite>(0);

	public Specialite() {
	}

	public Specialite(String nomSpecialite, String commentaire) {
		this.nomSpecialite = nomSpecialite;
		this.commentaire = commentaire;
	}

	public Specialite(String nomSpecialite, String commentaire, Set<Gite> gites) {
		this.nomSpecialite = nomSpecialite;
		this.commentaire = commentaire;
		this.gites = gites;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSpecialite", unique = true, nullable = false)
	public Integer getIdSpecialite() {
		return this.idSpecialite;
	}

	public void setIdSpecialite(Integer idSpecialite) {
		this.idSpecialite = idSpecialite;
	}

	@Column(name = "nomSpecialite", nullable = false, length = 100)
	public String getNomSpecialite() {
		return this.nomSpecialite;
	}

	public void setNomSpecialite(String nomSpecialite) {
		this.nomSpecialite = nomSpecialite;
	}

	@Column(name = "commentaire", nullable = false, length = 65535)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "link_gitespecialite", catalog = "gestion_gite", joinColumns = { @JoinColumn(name = "idSpecialite", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "igGite", nullable = false, updatable = false) })
	public Set<Gite> getGites() {
		return this.gites;
	}

	public void setGites(Set<Gite> gites) {
		this.gites = gites;
	}

}
