package pojo;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tarif generated by hbm2java
 */
@Entity
@Table(name = "tarif", catalog = "gestion_gite")
public class Tarif implements java.io.Serializable {

	private TarifId id;
	private Typetarif typetarif;
	private Typelocation typelocation;
	private double prixLocation;

	public Tarif() {
	}

	public Tarif(TarifId id, Typetarif typetarif, Typelocation typelocation,
			double prixLocation) {
		this.id = id;
		this.typetarif = typetarif;
		this.typelocation = typelocation;
		this.prixLocation = prixLocation;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idType", column = @Column(name = "idType", nullable = false)),
			@AttributeOverride(name = "idTypeLocation", column = @Column(name = "idTypeLocation", nullable = false)) })
	public TarifId getId() {
		return this.id;
	}

	public void setId(TarifId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idType", nullable = false, insertable = false, updatable = false)
	public Typetarif getTypetarif() {
		return this.typetarif;
	}

	public void setTypetarif(Typetarif typetarif) {
		this.typetarif = typetarif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTypeLocation", nullable = false, insertable = false, updatable = false)
	public Typelocation getTypelocation() {
		return this.typelocation;
	}

	public void setTypelocation(Typelocation typelocation) {
		this.typelocation = typelocation;
	}

	@Column(name = "prixLocation", nullable = false, precision = 22, scale = 0)
	public double getPrixLocation() {
		return this.prixLocation;
	}

	public void setPrixLocation(double prixLocation) {
		this.prixLocation = prixLocation;
	}

}
