package pojo;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typetarif generated by hbm2java
 */
@Entity
@Table(name = "typetarif", catalog = "gestion_gite")
public class Typetarif implements java.io.Serializable {

	private Integer idType;
	private String type;
	private Set<Tarif> tarifs = new HashSet<Tarif>(0);

	public Typetarif() {
	}

	public Typetarif(String type) {
		this.type = type;
	}

	public Typetarif(String type, Set<Tarif> tarifs) {
		this.type = type;
		this.tarifs = tarifs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idType", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typetarif")
	public Set<Tarif> getTarifs() {
		return this.tarifs;
	}

	public void setTarifs(Set<Tarif> tarifs) {
		this.tarifs = tarifs;
	}

}
