package recuperation;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkGiteactiviteId generated by hbm2java
 */
@Embeddable
public class LinkGiteactiviteId implements java.io.Serializable {

	private int idActivite;
	private int idGite;

	public LinkGiteactiviteId() {
	}

	public LinkGiteactiviteId(int idActivite, int idGite) {
		this.idActivite = idActivite;
		this.idGite = idGite;
	}

	@Column(name = "idActivite", nullable = false)
	public int getIdActivite() {
		return this.idActivite;
	}

	public void setIdActivite(int idActivite) {
		this.idActivite = idActivite;
	}

	@Column(name = "idGite", nullable = false)
	public int getIdGite() {
		return this.idGite;
	}

	public void setIdGite(int idGite) {
		this.idGite = idGite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinkGiteactiviteId))
			return false;
		LinkGiteactiviteId castOther = (LinkGiteactiviteId) other;

		return (this.getIdActivite() == castOther.getIdActivite())
				&& (this.getIdGite() == castOther.getIdGite());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdActivite();
		result = 37 * result + this.getIdGite();
		return result;
	}

}
