package recuperation;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name = "pays", catalog = "gestion_gite", uniqueConstraints = @UniqueConstraint(columnNames = "nomPays"))
public class Pays implements java.io.Serializable {

	private int idPays;
	private String nomPays;
	private Set<Adresse> adresses = new HashSet<Adresse>(0);

	public Pays() {
	}

	public Pays(int idPays, String nomPays) {
		this.idPays = idPays;
		this.nomPays = nomPays;
	}

	public Pays(int idPays, String nomPays, Set<Adresse> adresses) {
		this.idPays = idPays;
		this.nomPays = nomPays;
		this.adresses = adresses;
	}

	@Id
	@Column(name = "idPays", unique = true, nullable = false)
	public int getIdPays() {
		return this.idPays;
	}

	public void setIdPays(int idPays) {
		this.idPays = idPays;
	}

	@Column(name = "nomPays", unique = true, nullable = false, length = 100)
	public String getNomPays() {
		return this.nomPays;
	}

	public void setNomPays(String nomPays) {
		this.nomPays = nomPays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	public Set<Adresse> getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Set<Adresse> adresses) {
		this.adresses = adresses;
	}

}
