package recuperation;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typegite generated by hbm2java
 */
@Entity
@Table(name = "typegite", catalog = "gestion_gite")
public class Typegite implements java.io.Serializable {

	private Integer idType;
	private String type;
	private Set<Gite> gites = new HashSet<Gite>(0);

	public Typegite() {
	}

	public Typegite(String type) {
		this.type = type;
	}

	public Typegite(String type, Set<Gite> gites) {
		this.type = type;
		this.gites = gites;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idType", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typegite")
	public Set<Gite> getGites() {
		return this.gites;
	}

	public void setGites(Set<Gite> gites) {
		this.gites = gites;
	}

}
