package recuperation;

// Generated 03-avr.-2014 20:24:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typeactivite generated by hbm2java
 */
@Entity
@Table(name = "typeactivite", catalog = "gestion_gite")
public class Typeactivite implements java.io.Serializable {

	private Integer idType;
	private String nomType;
	private Set<Activite> activites = new HashSet<Activite>(0);

	public Typeactivite() {
	}

	public Typeactivite(String nomType) {
		this.nomType = nomType;
	}

	public Typeactivite(String nomType, Set<Activite> activites) {
		this.nomType = nomType;
		this.activites = activites;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idType", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "nomType", nullable = false, length = 20)
	public String getNomType() {
		return this.nomType;
	}

	public void setNomType(String nomType) {
		this.nomType = nomType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeactivite")
	public Set<Activite> getActivites() {
		return this.activites;
	}

	public void setActivites(Set<Activite> activites) {
		this.activites = activites;
	}

}
